// ============================================================================
// Purp program templates for the scaffold tool
// ============================================================================

export interface PurpTemplate {
  name: string;
  description: string;
  source: string;
}

export const TEMPLATES: Record<string, PurpTemplate> = {
  token: {
    name: 'SPL Token',
    description: 'A basic SPL token with mint, transfer, and burn instructions.',
    source: `// {name} — SPL Token Program
// Generated by Sigil (https://github.com/DosukaSOL/sigil)

import { Token } from "@purp/stdlib";

program {name} {

  account TokenVault {
    authority: pubkey,
    total_supply: u64,
    decimals: u8,
    is_frozen: bool
  }

  pub instruction initialize(
    #[mut] signer authority,
    #[init] account vault,
    decimals: u8,
    initial_supply: u64
  ) {
    vault.authority = authority;
    vault.decimals = decimals;
    vault.total_supply = initial_supply;
    vault.is_frozen = false;
    emit TokenInitialized(authority, decimals, initial_supply);
  }

  pub instruction mint(
    #[mut] signer authority,
    #[mut] account vault,
    recipient: pubkey,
    amount: u64
  ) {
    assert(vault.authority == authority, "Unauthorized");
    assert(vault.is_frozen == false, "Token is frozen");
    vault.total_supply += amount;
    emit TokensMinted(recipient, amount);
  }

  pub instruction transfer(
    #[mut] signer sender,
    #[mut] account vault,
    recipient: pubkey,
    amount: u64
  ) {
    assert(vault.is_frozen == false, "Token is frozen");
    emit TokensTransferred(sender, recipient, amount);
  }

  pub instruction burn(
    #[mut] signer holder,
    #[mut] account vault,
    amount: u64
  ) {
    assert(vault.total_supply >= amount, "Insufficient supply");
    vault.total_supply -= amount;
    emit TokensBurned(holder, amount);
  }

  pub instruction freeze(
    #[mut] signer authority,
    #[mut] account vault
  ) {
    assert(vault.authority == authority, "Unauthorized");
    vault.is_frozen = true;
    emit TokenFrozen(authority);
  }

  event TokenInitialized { authority: pubkey, decimals: u8, supply: u64 }
  event TokensMinted { recipient: pubkey, amount: u64 }
  event TokensTransferred { sender: pubkey, recipient: pubkey, amount: u64 }
  event TokensBurned { holder: pubkey, amount: u64 }
  event TokenFrozen { authority: pubkey }

  error TokenErrors {
    Unauthorized = "You are not the mint authority",
    InsufficientSupply = "Not enough tokens to burn",
    Frozen = "Token is frozen"
  }
}
`,
  },

  escrow: {
    name: 'Escrow',
    description: 'A trustless escrow program for peer-to-peer trades.',
    source: `// {name} — Escrow Program
// Generated by Sigil (https://github.com/DosukaSOL/sigil)

program {name} {

  account Escrow {
    maker: pubkey,
    taker: pubkey,
    amount: u64,
    receive_amount: u64,
    status: u8,
    deadline: u64
  }

  pub instruction create_escrow(
    #[mut] signer maker,
    #[init] account escrow,
    amount: u64,
    receive_amount: u64,
    deadline: u64
  ) {
    escrow.maker = maker;
    escrow.amount = amount;
    escrow.receive_amount = receive_amount;
    escrow.status = 0;
    escrow.deadline = deadline;
    emit EscrowCreated(maker, amount, receive_amount);
  }

  pub instruction accept_escrow(
    #[mut] signer taker,
    #[mut] account escrow
  ) {
    assert(escrow.status == 0, "Escrow not available");
    escrow.taker = taker;
    escrow.status = 1;
    emit EscrowAccepted(taker, escrow.amount);
  }

  pub instruction complete_escrow(
    #[mut] signer maker,
    #[mut] account escrow
  ) {
    assert(escrow.status == 1, "Escrow not accepted");
    assert(escrow.maker == maker, "Not the maker");
    escrow.status = 2;
    emit EscrowCompleted(escrow.maker, escrow.taker, escrow.amount);
  }

  pub instruction cancel_escrow(
    #[mut] signer maker,
    #[mut] account escrow
  ) {
    assert(escrow.maker == maker, "Not the maker");
    assert(escrow.status == 0, "Cannot cancel after acceptance");
    escrow.status = 3;
    emit EscrowCancelled(maker);
  }

  event EscrowCreated { maker: pubkey, amount: u64, receive_amount: u64 }
  event EscrowAccepted { taker: pubkey, amount: u64 }
  event EscrowCompleted { maker: pubkey, taker: pubkey, amount: u64 }
  event EscrowCancelled { maker: pubkey }

  error EscrowErrors {
    NotAvailable = "Escrow is not available",
    Unauthorized = "You are not authorized",
    AlreadyAccepted = "Escrow already accepted"
  }
}
`,
  },

  staking: {
    name: 'Staking Rewards',
    description: 'A staking program with configurable rewards and lock periods.',
    source: `// {name} — Staking Rewards Program
// Generated by Sigil (https://github.com/DosukaSOL/sigil)

program {name} {

  account StakePool {
    authority: pubkey,
    total_staked: u64,
    reward_rate: u64,
    min_stake: u64,
    lock_period: u64,
    is_active: bool
  }

  account StakeInfo {
    owner: pubkey,
    amount: u64,
    staked_at: u64,
    last_claim: u64,
    rewards_earned: u64
  }

  pub instruction initialize_pool(
    #[mut] signer authority,
    #[init] account pool,
    reward_rate: u64,
    min_stake: u64,
    lock_period: u64
  ) {
    pool.authority = authority;
    pool.total_staked = 0;
    pool.reward_rate = reward_rate;
    pool.min_stake = min_stake;
    pool.lock_period = lock_period;
    pool.is_active = true;
    emit PoolInitialized(authority, reward_rate);
  }

  pub instruction stake(
    #[mut] signer staker,
    #[mut] account pool,
    #[init] account info,
    amount: u64
  ) {
    assert(pool.is_active == true, "Pool is inactive");
    assert(amount >= pool.min_stake, "Below minimum stake");
    info.owner = staker;
    info.amount = amount;
    info.staked_at = Clock.slot;
    info.last_claim = Clock.slot;
    info.rewards_earned = 0;
    pool.total_staked += amount;
    emit Staked(staker, amount);
  }

  pub instruction claim_rewards(
    #[mut] signer staker,
    #[mut] account pool,
    #[mut] account info
  ) {
    assert(info.owner == staker, "Not the staker");
    let elapsed = Clock.slot - info.last_claim;
    let reward = elapsed * pool.reward_rate * info.amount / 1000000;
    info.rewards_earned += reward;
    info.last_claim = Clock.slot;
    emit RewardsClaimed(staker, reward);
  }

  pub instruction unstake(
    #[mut] signer staker,
    #[mut] account pool,
    #[mut] account info
  ) {
    assert(info.owner == staker, "Not the staker");
    let elapsed = Clock.slot - info.staked_at;
    assert(elapsed >= pool.lock_period, "Lock period not met");
    pool.total_staked -= info.amount;
    emit Unstaked(staker, info.amount);
  }

  event PoolInitialized { authority: pubkey, reward_rate: u64 }
  event Staked { staker: pubkey, amount: u64 }
  event RewardsClaimed { staker: pubkey, reward: u64 }
  event Unstaked { staker: pubkey, amount: u64 }

  error StakingErrors {
    PoolInactive = "Staking pool is not active",
    BelowMinimum = "Stake amount below minimum",
    LockNotMet = "Lock period has not elapsed"
  }
}
`,
  },

  dao: {
    name: 'DAO Governance',
    description: 'A DAO with proposals, voting, and treasury management.',
    source: `// {name} — DAO Governance Program
// Generated by Sigil (https://github.com/DosukaSOL/sigil)

program {name} {

  account DAO {
    authority: pubkey,
    name: string,
    member_count: u64,
    proposal_count: u64,
    quorum: u64,
    voting_period: u64,
    treasury_balance: u64
  }

  account Proposal {
    proposer: pubkey,
    title: string,
    description: string,
    votes_for: u64,
    votes_against: u64,
    status: u8,
    created_at: u64,
    amount: u64
  }

  account Member {
    member_addr: pubkey,
    voting_power: u64,
    joined_at: u64,
    proposals_created: u64
  }

  pub instruction create_dao(
    #[mut] signer authority,
    #[init] account dao,
    name: string,
    quorum: u64,
    voting_period: u64
  ) {
    dao.authority = authority;
    dao.name = name;
    dao.member_count = 1;
    dao.proposal_count = 0;
    dao.quorum = quorum;
    dao.voting_period = voting_period;
    dao.treasury_balance = 0;
    emit DAOCreated(authority, name);
  }

  pub instruction add_member(
    #[mut] signer authority,
    #[mut] account dao,
    #[init] account member,
    member_addr: pubkey,
    voting_power: u64
  ) {
    assert(dao.authority == authority, "Not the DAO authority");
    member.member_addr = member_addr;
    member.voting_power = voting_power;
    member.joined_at = Clock.slot;
    member.proposals_created = 0;
    dao.member_count += 1;
    emit MemberAdded(member_addr, voting_power);
  }

  pub instruction create_proposal(
    #[mut] signer proposer,
    #[mut] account dao,
    #[init] account proposal,
    #[mut] account member,
    title: string,
    description: string,
    amount: u64
  ) {
    assert(member.member_addr == proposer, "Not a member");
    proposal.proposer = proposer;
    proposal.title = title;
    proposal.description = description;
    proposal.votes_for = 0;
    proposal.votes_against = 0;
    proposal.status = 0;
    proposal.created_at = Clock.slot;
    proposal.amount = amount;
    dao.proposal_count += 1;
    member.proposals_created += 1;
    emit ProposalCreated(proposer, title);
  }

  pub instruction vote(
    #[mut] signer voter,
    #[mut] account proposal,
    #[mut] account member,
    in_favor: bool
  ) {
    assert(member.member_addr == voter, "Not a member");
    assert(proposal.status == 0, "Voting closed");
    if in_favor {
      proposal.votes_for += member.voting_power;
    } else {
      proposal.votes_against += member.voting_power;
    }
    emit Voted(voter, in_favor);
  }

  pub instruction execute_proposal(
    #[mut] signer authority,
    #[mut] account dao,
    #[mut] account proposal
  ) {
    assert(dao.authority == authority, "Not authority");
    assert(proposal.status == 0, "Already executed");
    assert(proposal.votes_for >= dao.quorum, "Quorum not met");
    assert(proposal.votes_for > proposal.votes_against, "Not enough votes");
    proposal.status = 1;
    emit ProposalExecuted(proposal.title, proposal.votes_for);
  }

  event DAOCreated { authority: pubkey, name: string }
  event MemberAdded { member_addr: pubkey, voting_power: u64 }
  event ProposalCreated { proposer: pubkey, title: string }
  event Voted { voter: pubkey, in_favor: bool }
  event ProposalExecuted { title: string, votes: u64 }

  error DAOErrors {
    Unauthorized = "You are not authorized",
    NotMember = "You are not a DAO member",
    QuorumNotMet = "Quorum threshold not reached",
    VotingClosed = "Voting period has ended"
  }
}
`,
  },

  nft: {
    name: 'NFT Collection',
    description: 'An NFT collection with mint, transfer, and metadata.',
    source: `// {name} — NFT Collection Program
// Generated by Sigil (https://github.com/DosukaSOL/sigil)

import { NFT } from "@purp/stdlib";

program {name} {

  account Collection {
    authority: pubkey,
    name: string,
    symbol: string,
    total_minted: u64,
    max_supply: u64,
    royalty_bps: u64,
    is_minting: bool
  }

  account NftMetadata {
    collection: pubkey,
    owner: pubkey,
    name: string,
    uri: string,
    mint_number: u64,
    is_listed: bool,
    price: u64
  }

  pub instruction create_collection(
    #[mut] signer authority,
    #[init] account collection,
    name: string,
    symbol: string,
    max_supply: u64,
    royalty_bps: u64
  ) {
    collection.authority = authority;
    collection.name = name;
    collection.symbol = symbol;
    collection.total_minted = 0;
    collection.max_supply = max_supply;
    collection.royalty_bps = royalty_bps;
    collection.is_minting = true;
    emit CollectionCreated(authority, name, max_supply);
  }

  pub instruction mint_nft(
    #[mut] signer minter,
    #[mut] account collection,
    #[init] account metadata,
    name: string,
    uri: string
  ) {
    assert(collection.is_minting == true, "Minting is closed");
    assert(collection.total_minted < collection.max_supply, "Max supply reached");
    collection.total_minted += 1;
    metadata.collection = collection;
    metadata.owner = minter;
    metadata.name = name;
    metadata.uri = uri;
    metadata.mint_number = collection.total_minted;
    metadata.is_listed = false;
    metadata.price = 0;
    emit NftMinted(minter, name, collection.total_minted);
  }

  pub instruction list_nft(
    #[mut] signer owner,
    #[mut] account metadata,
    price: u64
  ) {
    assert(metadata.owner == owner, "Not the owner");
    assert(price > 0, "Price must be positive");
    metadata.is_listed = true;
    metadata.price = price;
    emit NftListed(owner, metadata.name, price);
  }

  pub instruction buy_nft(
    #[mut] signer buyer,
    #[mut] account metadata,
    #[mut] account collection
  ) {
    assert(metadata.is_listed == true, "NFT not listed");
    metadata.owner = buyer;
    metadata.is_listed = false;
    metadata.price = 0;
    emit NftSold(buyer, metadata.name);
  }

  pub instruction close_minting(
    #[mut] signer authority,
    #[mut] account collection
  ) {
    assert(collection.authority == authority, "Unauthorized");
    collection.is_minting = false;
    emit MintingClosed(authority);
  }

  event CollectionCreated { authority: pubkey, name: string, max_supply: u64 }
  event NftMinted { minter: pubkey, name: string, number: u64 }
  event NftListed { owner: pubkey, name: string, price: u64 }
  event NftSold { buyer: pubkey, name: string }
  event MintingClosed { authority: pubkey }

  error NftErrors {
    MintingClosed = "Minting is closed",
    MaxSupply = "Maximum supply reached",
    NotOwner = "You do not own this NFT",
    NotListed = "NFT is not listed for sale"
  }
}
`,
  },

  game: {
    name: 'Onchain Game',
    description: 'A simple on-chain game with player state, scores, and leaderboard.',
    source: `// {name} — On-Chain Game Program
// Generated by Sigil (https://github.com/DosukaSOL/sigil)

program {name} {

  account GameState {
    authority: pubkey,
    game_name: string,
    player_count: u64,
    prize_pool: u64,
    round: u64,
    is_active: bool
  }

  account Player {
    player_addr: pubkey,
    score: u64,
    games_played: u64,
    wins: u64,
    joined_at: u64
  }

  pub instruction create_game(
    #[mut] signer authority,
    #[init] account game,
    game_name: string
  ) {
    game.authority = authority;
    game.game_name = game_name;
    game.player_count = 0;
    game.prize_pool = 0;
    game.round = 1;
    game.is_active = true;
    emit GameCreated(authority, game_name);
  }

  pub instruction register_player(
    #[mut] signer player_signer,
    #[mut] account game,
    #[init] account player
  ) {
    assert(game.is_active == true, "Game is not active");
    player.player_addr = player_signer;
    player.score = 0;
    player.games_played = 0;
    player.wins = 0;
    player.joined_at = Clock.slot;
    game.player_count += 1;
    emit PlayerRegistered(player_signer);
  }

  pub instruction play_round(
    #[mut] signer player_signer,
    #[mut] account game,
    #[mut] account player,
    score: u64
  ) {
    assert(game.is_active == true, "Game is not active");
    assert(player.player_addr == player_signer, "Not your player");
    player.score += score;
    player.games_played += 1;
    emit RoundPlayed(player_signer, score, player.score);
  }

  pub instruction claim_win(
    #[mut] signer player_signer,
    #[mut] account game,
    #[mut] account player
  ) {
    assert(player.player_addr == player_signer, "Not your player");
    player.wins += 1;
    emit WinClaimed(player_signer, player.wins);
  }

  pub instruction end_game(
    #[mut] signer authority,
    #[mut] account game
  ) {
    assert(game.authority == authority, "Unauthorized");
    game.is_active = false;
    game.round += 1;
    emit GameEnded(authority, game.round);
  }

  event GameCreated { authority: pubkey, name: string }
  event PlayerRegistered { player_addr: pubkey }
  event RoundPlayed { player: pubkey, round_score: u64, total_score: u64 }
  event WinClaimed { player: pubkey, total_wins: u64 }
  event GameEnded { authority: pubkey, round: u64 }

  error GameErrors {
    NotActive = "Game is not active",
    Unauthorized = "You are not authorized",
    NotYourPlayer = "This is not your player account"
  }
}
`,
  },

  amm: {
    name: 'AMM DEX',
    description: 'An automated market maker with liquidity pools, swaps, and LP tokens.',
    source: `// {name} — Automated Market Maker
// Generated by Sigil (https://github.com/DosukaSOL/sigil)

program {name} {

  account Pool {
    authority: pubkey,
    token_a_reserve: u64,
    token_b_reserve: u64,
    lp_supply: u64,
    fee_bps: u64,
    is_active: bool
  }

  account LpPosition {
    owner: pubkey,
    pool: pubkey,
    lp_tokens: u64,
    deposited_at: u64
  }

  pub instruction create_pool(
    #[mut] signer authority,
    #[init] account pool,
    fee_bps: u64
  ) {
    assert(fee_bps <= 1000, "Fee too high");
    pool.authority = authority;
    pool.token_a_reserve = 0;
    pool.token_b_reserve = 0;
    pool.lp_supply = 0;
    pool.fee_bps = fee_bps;
    pool.is_active = true;
    emit PoolCreated(authority, fee_bps);
  }

  pub instruction add_liquidity(
    #[mut] signer provider,
    #[mut] account pool,
    #[init] account position,
    amount_a: u64,
    amount_b: u64
  ) {
    assert(pool.is_active == true, "Pool inactive");
    assert(amount_a > 0, "Amount A must be positive");
    assert(amount_b > 0, "Amount B must be positive");
    let lp_minted = amount_a;
    if pool.lp_supply > 0 {
      lp_minted = amount_a * pool.lp_supply / pool.token_a_reserve;
    }
    pool.token_a_reserve += amount_a;
    pool.token_b_reserve += amount_b;
    pool.lp_supply += lp_minted;
    position.owner = provider;
    position.pool = pool;
    position.lp_tokens = lp_minted;
    position.deposited_at = Clock.slot;
    emit LiquidityAdded(provider, amount_a, amount_b, lp_minted);
  }

  pub instruction swap_a_to_b(
    #[mut] signer trader,
    #[mut] account pool,
    amount_in: u64,
    min_out: u64
  ) {
    assert(pool.is_active == true, "Pool inactive");
    assert(amount_in > 0, "Amount must be positive");
    let fee = amount_in * pool.fee_bps / 10000;
    let net_in = amount_in - fee;
    let amount_out = net_in * pool.token_b_reserve / (pool.token_a_reserve + net_in);
    assert(amount_out >= min_out, "Slippage exceeded");
    pool.token_a_reserve += amount_in;
    pool.token_b_reserve -= amount_out;
    emit Swapped(trader, amount_in, amount_out);
  }

  pub instruction swap_b_to_a(
    #[mut] signer trader,
    #[mut] account pool,
    amount_in: u64,
    min_out: u64
  ) {
    assert(pool.is_active == true, "Pool inactive");
    assert(amount_in > 0, "Amount must be positive");
    let fee = amount_in * pool.fee_bps / 10000;
    let net_in = amount_in - fee;
    let amount_out = net_in * pool.token_a_reserve / (pool.token_b_reserve + net_in);
    assert(amount_out >= min_out, "Slippage exceeded");
    pool.token_b_reserve += amount_in;
    pool.token_a_reserve -= amount_out;
    emit Swapped(trader, amount_in, amount_out);
  }

  pub instruction remove_liquidity(
    #[mut] signer provider,
    #[mut] account pool,
    #[mut] account position
  ) {
    assert(position.owner == provider, "Not the LP owner");
    assert(position.lp_tokens > 0, "No LP tokens");
    let share_a = position.lp_tokens * pool.token_a_reserve / pool.lp_supply;
    let share_b = position.lp_tokens * pool.token_b_reserve / pool.lp_supply;
    pool.token_a_reserve -= share_a;
    pool.token_b_reserve -= share_b;
    pool.lp_supply -= position.lp_tokens;
    position.lp_tokens = 0;
    emit LiquidityRemoved(provider, share_a, share_b);
  }

  event PoolCreated { authority: pubkey, fee_bps: u64 }
  event LiquidityAdded { provider: pubkey, amount_a: u64, amount_b: u64, lp_minted: u64 }
  event Swapped { trader: pubkey, amount_in: u64, amount_out: u64 }
  event LiquidityRemoved { provider: pubkey, amount_a: u64, amount_b: u64 }

  error AmmErrors {
    PoolInactive = "Pool is not active",
    SlippageExceeded = "Output amount below minimum",
    ZeroAmount = "Amount must be greater than zero",
    FeeTooHigh = "Fee exceeds maximum basis points"
  }
}
`,
  },

  multisig: {
    name: 'Multisig Wallet',
    description: 'A multi-signature wallet with threshold-based transaction approval.',
    source: `// {name} — Multisig Wallet Program
// Generated by Sigil (https://github.com/DosukaSOL/sigil)

program {name} {

  account Multisig {
    threshold: u64,
    owner_count: u64,
    transaction_count: u64,
    is_active: bool
  }

  account Owner {
    owner_addr: pubkey,
    multisig: pubkey,
    index: u64,
    is_active: bool
  }

  account Transaction {
    multisig: pubkey,
    proposer: pubkey,
    recipient: pubkey,
    amount: u64,
    approvals: u64,
    is_executed: bool,
    created_at: u64
  }

  pub instruction create_multisig(
    #[mut] signer creator,
    #[init] account multisig,
    #[init] account owner,
    threshold: u64
  ) {
    assert(threshold >= 1, "Threshold must be at least 1");
    multisig.threshold = threshold;
    multisig.owner_count = 1;
    multisig.transaction_count = 0;
    multisig.is_active = true;
    owner.owner_addr = creator;
    owner.multisig = multisig;
    owner.index = 0;
    owner.is_active = true;
    emit MultisigCreated(creator, threshold);
  }

  pub instruction add_owner(
    #[mut] signer authority,
    #[mut] account multisig,
    #[mut] account existing_owner,
    #[init] account new_owner,
    owner_addr: pubkey
  ) {
    assert(existing_owner.owner_addr == authority, "Not an owner");
    assert(existing_owner.is_active == true, "Owner inactive");
    new_owner.owner_addr = owner_addr;
    new_owner.multisig = multisig;
    new_owner.index = multisig.owner_count;
    new_owner.is_active = true;
    multisig.owner_count += 1;
    emit OwnerAdded(owner_addr, multisig.owner_count);
  }

  pub instruction propose_transaction(
    #[mut] signer proposer,
    #[mut] account multisig,
    #[mut] account owner,
    #[init] account txn,
    recipient: pubkey,
    amount: u64
  ) {
    assert(owner.owner_addr == proposer, "Not an owner");
    assert(owner.is_active == true, "Owner inactive");
    txn.multisig = multisig;
    txn.proposer = proposer;
    txn.recipient = recipient;
    txn.amount = amount;
    txn.approvals = 1;
    txn.is_executed = false;
    txn.created_at = Clock.slot;
    multisig.transaction_count += 1;
    emit TransactionProposed(proposer, recipient, amount);
  }

  pub instruction approve(
    #[mut] signer approver,
    #[mut] account txn,
    #[mut] account owner
  ) {
    assert(owner.owner_addr == approver, "Not an owner");
    assert(owner.is_active == true, "Owner inactive");
    assert(txn.is_executed == false, "Already executed");
    txn.approvals += 1;
    emit TransactionApproved(approver, txn.approvals);
  }

  pub instruction execute_transaction(
    #[mut] signer executor,
    #[mut] account multisig,
    #[mut] account txn,
    #[mut] account owner
  ) {
    assert(owner.owner_addr == executor, "Not an owner");
    assert(txn.is_executed == false, "Already executed");
    assert(txn.approvals >= multisig.threshold, "Not enough approvals");
    txn.is_executed = true;
    emit TransactionExecuted(executor, txn.recipient, txn.amount);
  }

  event MultisigCreated { creator: pubkey, threshold: u64 }
  event OwnerAdded { owner_addr: pubkey, total_owners: u64 }
  event TransactionProposed { proposer: pubkey, recipient: pubkey, amount: u64 }
  event TransactionApproved { approver: pubkey, total_approvals: u64 }
  event TransactionExecuted { executor: pubkey, recipient: pubkey, amount: u64 }

  error MultisigErrors {
    NotOwner = "You are not an owner of this multisig",
    InsufficientApprovals = "Not enough approvals to execute",
    AlreadyExecuted = "Transaction has already been executed",
    OwnerInactive = "Owner account is not active"
  }
}
`,
  },

  auction: {
    name: 'Auction House',
    description: 'A timed auction with bidding, auto-extension, and settlement.',
    source: `// {name} — Auction House Program
// Generated by Sigil (https://github.com/DosukaSOL/sigil)

program {name} {

  account AuctionHouse {
    authority: pubkey,
    fee_bps: u64,
    total_auctions: u64,
    total_volume: u64
  }

  account Auction {
    seller: pubkey,
    highest_bidder: pubkey,
    highest_bid: u64,
    reserve_price: u64,
    start_time: u64,
    end_time: u64,
    bid_count: u64,
    is_settled: bool
  }

  pub instruction create_auction_house(
    #[mut] signer authority,
    #[init] account house,
    fee_bps: u64
  ) {
    assert(fee_bps <= 500, "Fee too high");
    house.authority = authority;
    house.fee_bps = fee_bps;
    house.total_auctions = 0;
    house.total_volume = 0;
    emit AuctionHouseCreated(authority, fee_bps);
  }

  pub instruction create_auction(
    #[mut] signer seller,
    #[mut] account house,
    #[init] account auction,
    reserve_price: u64,
    duration: u64
  ) {
    assert(reserve_price > 0, "Reserve must be positive");
    assert(duration > 0, "Duration must be positive");
    auction.seller = seller;
    auction.highest_bidder = seller;
    auction.highest_bid = 0;
    auction.reserve_price = reserve_price;
    auction.start_time = Clock.slot;
    auction.end_time = Clock.slot + duration;
    auction.bid_count = 0;
    auction.is_settled = false;
    house.total_auctions += 1;
    emit AuctionCreated(seller, reserve_price, duration);
  }

  pub instruction place_bid(
    #[mut] signer bidder,
    #[mut] account auction,
    amount: u64
  ) {
    assert(auction.is_settled == false, "Auction settled");
    assert(amount > auction.highest_bid, "Bid too low");
    assert(amount >= auction.reserve_price, "Below reserve");
    auction.highest_bidder = bidder;
    auction.highest_bid = amount;
    auction.bid_count += 1;
    emit BidPlaced(bidder, amount, auction.bid_count);
  }

  pub instruction settle_auction(
    #[mut] signer authority,
    #[mut] account house,
    #[mut] account auction
  ) {
    assert(auction.is_settled == false, "Already settled");
    assert(auction.bid_count > 0, "No bids placed");
    auction.is_settled = true;
    let fee = auction.highest_bid * house.fee_bps / 10000;
    let seller_amount = auction.highest_bid - fee;
    house.total_volume += auction.highest_bid;
    emit AuctionSettled(auction.seller, auction.highest_bidder, seller_amount);
  }

  pub instruction cancel_auction(
    #[mut] signer seller,
    #[mut] account auction
  ) {
    assert(auction.seller == seller, "Not the seller");
    assert(auction.bid_count == 0, "Has bids, cannot cancel");
    auction.is_settled = true;
    emit AuctionCancelled(seller);
  }

  event AuctionHouseCreated { authority: pubkey, fee_bps: u64 }
  event AuctionCreated { seller: pubkey, reserve: u64, duration: u64 }
  event BidPlaced { bidder: pubkey, amount: u64, bid_number: u64 }
  event AuctionSettled { seller: pubkey, winner: pubkey, amount: u64 }
  event AuctionCancelled { seller: pubkey }

  error AuctionErrors {
    BidTooLow = "Bid must exceed current highest bid",
    BelowReserve = "Bid is below the reserve price",
    AuctionEnded = "Auction has already ended",
    NoBids = "No bids were placed"
  }
}
`,
  },

  lending: {
    name: 'Lending Protocol',
    description: 'A lending/borrowing protocol with collateral, interest, and liquidation.',
    source: `// {name} — Lending Protocol
// Generated by Sigil (https://github.com/DosukaSOL/sigil)

program {name} {

  account LendingPool {
    authority: pubkey,
    total_deposits: u64,
    total_borrows: u64,
    interest_rate_bps: u64,
    collateral_ratio: u64,
    is_active: bool
  }

  account Deposit {
    owner: pubkey,
    pool: pubkey,
    amount: u64,
    deposited_at: u64,
    interest_earned: u64
  }

  account Loan {
    borrower: pubkey,
    pool: pubkey,
    principal: u64,
    collateral: u64,
    interest_accrued: u64,
    borrowed_at: u64,
    is_liquidated: bool
  }

  pub instruction create_pool(
    #[mut] signer authority,
    #[init] account pool,
    interest_rate_bps: u64,
    collateral_ratio: u64
  ) {
    assert(interest_rate_bps <= 5000, "Interest rate too high");
    assert(collateral_ratio >= 100, "Collateral ratio too low");
    pool.authority = authority;
    pool.total_deposits = 0;
    pool.total_borrows = 0;
    pool.interest_rate_bps = interest_rate_bps;
    pool.collateral_ratio = collateral_ratio;
    pool.is_active = true;
    emit PoolCreated(authority, interest_rate_bps, collateral_ratio);
  }

  pub instruction deposit(
    #[mut] signer depositor,
    #[mut] account pool,
    #[init] account deposit,
    amount: u64
  ) {
    assert(pool.is_active == true, "Pool inactive");
    assert(amount > 0, "Amount must be positive");
    deposit.owner = depositor;
    deposit.pool = pool;
    deposit.amount = amount;
    deposit.deposited_at = Clock.slot;
    deposit.interest_earned = 0;
    pool.total_deposits += amount;
    emit Deposited(depositor, amount);
  }

  pub instruction borrow(
    #[mut] signer borrower,
    #[mut] account pool,
    #[init] account loan,
    principal: u64,
    collateral: u64
  ) {
    assert(pool.is_active == true, "Pool inactive");
    assert(principal > 0, "Amount must be positive");
    let required_collateral = principal * pool.collateral_ratio / 100;
    assert(collateral >= required_collateral, "Insufficient collateral");
    assert(pool.total_deposits - pool.total_borrows >= principal, "Insufficient liquidity");
    loan.borrower = borrower;
    loan.pool = pool;
    loan.principal = principal;
    loan.collateral = collateral;
    loan.interest_accrued = 0;
    loan.borrowed_at = Clock.slot;
    loan.is_liquidated = false;
    pool.total_borrows += principal;
    emit Borrowed(borrower, principal, collateral);
  }

  pub instruction repay(
    #[mut] signer borrower,
    #[mut] account pool,
    #[mut] account loan,
    amount: u64
  ) {
    assert(loan.borrower == borrower, "Not the borrower");
    assert(loan.is_liquidated == false, "Loan liquidated");
    assert(amount <= loan.principal, "Overpayment");
    loan.principal -= amount;
    pool.total_borrows -= amount;
    emit Repaid(borrower, amount, loan.principal);
  }

  pub instruction liquidate(
    #[mut] signer liquidator,
    #[mut] account pool,
    #[mut] account loan
  ) {
    assert(loan.is_liquidated == false, "Already liquidated");
    let required = loan.principal * pool.collateral_ratio / 100;
    assert(loan.collateral < required, "Loan is healthy");
    loan.is_liquidated = true;
    pool.total_borrows -= loan.principal;
    emit Liquidated(liquidator, loan.borrower, loan.principal);
  }

  pub instruction withdraw(
    #[mut] signer depositor,
    #[mut] account pool,
    #[mut] account deposit
  ) {
    assert(deposit.owner == depositor, "Not the depositor");
    assert(deposit.amount > 0, "Nothing to withdraw");
    assert(pool.total_deposits - pool.total_borrows >= deposit.amount, "Insufficient liquidity");
    pool.total_deposits -= deposit.amount;
    deposit.amount = 0;
    emit Withdrawn(depositor, deposit.amount);
  }

  event PoolCreated { authority: pubkey, rate: u64, ratio: u64 }
  event Deposited { depositor: pubkey, amount: u64 }
  event Borrowed { borrower: pubkey, principal: u64, collateral: u64 }
  event Repaid { borrower: pubkey, amount: u64, remaining: u64 }
  event Liquidated { liquidator: pubkey, borrower: pubkey, amount: u64 }
  event Withdrawn { depositor: pubkey, amount: u64 }

  error LendingErrors {
    InsufficientCollateral = "Not enough collateral for this loan",
    InsufficientLiquidity = "Pool does not have enough liquidity",
    LoanHealthy = "Loan cannot be liquidated, collateral is sufficient",
    NotBorrower = "You are not the borrower"
  }
}
`,
  },

  vesting: {
    name: 'Token Vesting',
    description: 'A token vesting schedule with cliff, linear unlock, and revocation.',
    source: `// {name} — Token Vesting Program
// Generated by Sigil (https://github.com/DosukaSOL/sigil)

program {name} {

  account VestingSchedule {
    authority: pubkey,
    beneficiary: pubkey,
    total_amount: u64,
    released_amount: u64,
    start_time: u64,
    cliff_duration: u64,
    total_duration: u64,
    is_revocable: bool,
    is_revoked: bool
  }

  pub instruction create_schedule(
    #[mut] signer authority,
    #[init] account schedule,
    beneficiary: pubkey,
    total_amount: u64,
    cliff_duration: u64,
    total_duration: u64,
    is_revocable: bool
  ) {
    assert(total_amount > 0, "Amount must be positive");
    assert(total_duration > 0, "Duration must be positive");
    assert(cliff_duration <= total_duration, "Cliff exceeds total duration");
    schedule.authority = authority;
    schedule.beneficiary = beneficiary;
    schedule.total_amount = total_amount;
    schedule.released_amount = 0;
    schedule.start_time = Clock.slot;
    schedule.cliff_duration = cliff_duration;
    schedule.total_duration = total_duration;
    schedule.is_revocable = is_revocable;
    schedule.is_revoked = false;
    emit ScheduleCreated(authority, beneficiary, total_amount, total_duration);
  }

  pub instruction claim(
    #[mut] signer beneficiary,
    #[mut] account schedule
  ) {
    assert(schedule.beneficiary == beneficiary, "Not the beneficiary");
    assert(schedule.is_revoked == false, "Schedule revoked");
    let elapsed = Clock.slot - schedule.start_time;
    assert(elapsed >= schedule.cliff_duration, "Cliff not reached");
    let vested = schedule.total_amount;
    if elapsed < schedule.total_duration {
      vested = schedule.total_amount * elapsed / schedule.total_duration;
    }
    let claimable = vested - schedule.released_amount;
    assert(claimable > 0, "Nothing to claim");
    schedule.released_amount += claimable;
    emit TokensClaimed(beneficiary, claimable, schedule.released_amount);
  }

  pub instruction revoke(
    #[mut] signer authority,
    #[mut] account schedule
  ) {
    assert(schedule.authority == authority, "Not the authority");
    assert(schedule.is_revocable == true, "Schedule is not revocable");
    assert(schedule.is_revoked == false, "Already revoked");
    schedule.is_revoked = true;
    let unvested = schedule.total_amount - schedule.released_amount;
    emit ScheduleRevoked(authority, unvested);
  }

  pub instruction transfer_beneficiary(
    #[mut] signer authority,
    #[mut] account schedule,
    new_beneficiary: pubkey
  ) {
    assert(schedule.authority == authority, "Not the authority");
    assert(schedule.is_revoked == false, "Schedule revoked");
    let old = schedule.beneficiary;
    schedule.beneficiary = new_beneficiary;
    emit BeneficiaryTransferred(old, new_beneficiary);
  }

  event ScheduleCreated { authority: pubkey, beneficiary: pubkey, amount: u64, duration: u64 }
  event TokensClaimed { beneficiary: pubkey, claimed: u64, total_released: u64 }
  event ScheduleRevoked { authority: pubkey, unvested_returned: u64 }
  event BeneficiaryTransferred { old: pubkey, new: pubkey }

  error VestingErrors {
    CliffNotReached = "Cliff period has not elapsed",
    NothingToClaim = "No tokens available to claim",
    NotRevocable = "Vesting schedule cannot be revoked",
    AlreadyRevoked = "Schedule has already been revoked"
  }
}
`,
  },
};

export function getTemplate(templateName: string, programName?: string): PurpTemplate | null {
  const key = templateName.toLowerCase().replace(/[\s-]/g, '');
  const aliases: Record<string, string> = {
    token: 'token',
    spl: 'token',
    spltoken: 'token',
    escrow: 'escrow',
    trade: 'escrow',
    swap: 'escrow',
    staking: 'staking',
    stake: 'staking',
    rewards: 'staking',
    dao: 'dao',
    governance: 'dao',
    vote: 'dao',
    voting: 'dao',
    nft: 'nft',
    collection: 'nft',
    mint: 'nft',
    game: 'game',
    gaming: 'game',
    onchain: 'game',
    amm: 'amm',
    dex: 'amm',
    liquiditypool: 'amm',
    lp: 'amm',
    multisig: 'multisig',
    multi: 'multisig',
    wallet: 'multisig',
    safe: 'multisig',
    auction: 'auction',
    bid: 'auction',
    auctionhouse: 'auction',
    lending: 'lending',
    borrow: 'lending',
    lend: 'lending',
    defi: 'lending',
    vesting: 'vesting',
    vest: 'vesting',
    unlock: 'vesting',
    cliff: 'vesting',
  };

  const resolved = aliases[key] ?? key;
  const template = TEMPLATES[resolved];
  if (!template) return null;

  const name = programName ?? template.name.replace(/\s+/g, '');
  return {
    ...template,
    source: template.source.replace(/\{name\}/g, name),
  };
}

export function listTemplates(): string {
  return Object.entries(TEMPLATES)
    .map(([key, t]) => `- **${key}**: ${t.name} — ${t.description}`)
    .join('\n');
}
