// ============================================================================
// Purp program templates for the scaffold tool
// ============================================================================

export interface PurpTemplate {
  name: string;
  description: string;
  source: string;
}

export const TEMPLATES: Record<string, PurpTemplate> = {
  token: {
    name: 'SPL Token',
    description: 'A basic SPL token with mint, transfer, and burn instructions.',
    source: `// {name} — SPL Token Program
// Generated by Sigil (https://github.com/DosukaSOL/sigil)

import { Token } from "@purp/stdlib";

program {name} {

  account TokenVault {
    authority: pubkey,
    total_supply: u64,
    decimals: u8,
    is_frozen: bool
  }

  pub instruction initialize(
    #[mut] signer authority,
    #[init] account vault,
    decimals: u8,
    initial_supply: u64
  ) {
    vault.authority = authority;
    vault.decimals = decimals;
    vault.total_supply = initial_supply;
    vault.is_frozen = false;
    emit TokenInitialized(authority, decimals, initial_supply);
  }

  pub instruction mint(
    #[mut] signer authority,
    #[mut] account vault,
    recipient: pubkey,
    amount: u64
  ) {
    assert(vault.authority == authority, "Unauthorized");
    assert(vault.is_frozen == false, "Token is frozen");
    vault.total_supply += amount;
    emit TokensMinted(recipient, amount);
  }

  pub instruction transfer(
    #[mut] signer from,
    #[mut] account vault,
    to: pubkey,
    amount: u64
  ) {
    assert(vault.is_frozen == false, "Token is frozen");
    emit TokensTransferred(from, to, amount);
  }

  pub instruction burn(
    #[mut] signer holder,
    #[mut] account vault,
    amount: u64
  ) {
    assert(vault.total_supply >= amount, "Insufficient supply");
    vault.total_supply -= amount;
    emit TokensBurned(holder, amount);
  }

  pub instruction freeze(
    #[mut] signer authority,
    #[mut] account vault
  ) {
    assert(vault.authority == authority, "Unauthorized");
    vault.is_frozen = true;
    emit TokenFrozen(authority);
  }

  event TokenInitialized { authority: pubkey, decimals: u8, supply: u64 }
  event TokensMinted { recipient: pubkey, amount: u64 }
  event TokensTransferred { from: pubkey, to: pubkey, amount: u64 }
  event TokensBurned { holder: pubkey, amount: u64 }
  event TokenFrozen { authority: pubkey }

  error TokenErrors {
    Unauthorized = "You are not the mint authority",
    InsufficientSupply = "Not enough tokens to burn",
    Frozen = "Token is frozen"
  }
}
`,
  },

  escrow: {
    name: 'Escrow',
    description: 'A trustless escrow program for peer-to-peer trades.',
    source: `// {name} — Escrow Program
// Generated by Sigil (https://github.com/DosukaSOL/sigil)

program {name} {

  account Escrow {
    maker: pubkey,
    taker: pubkey,
    amount: u64,
    receive_amount: u64,
    status: u8,
    deadline: u64
  }

  pub instruction create_escrow(
    #[mut] signer maker,
    #[init] account escrow,
    amount: u64,
    receive_amount: u64,
    deadline: u64
  ) {
    escrow.maker = maker;
    escrow.amount = amount;
    escrow.receive_amount = receive_amount;
    escrow.status = 0;
    escrow.deadline = deadline;
    emit EscrowCreated(maker, amount, receive_amount);
  }

  pub instruction accept_escrow(
    #[mut] signer taker,
    #[mut] account escrow
  ) {
    assert(escrow.status == 0, "Escrow not available");
    escrow.taker = taker;
    escrow.status = 1;
    emit EscrowAccepted(taker, escrow.amount);
  }

  pub instruction complete_escrow(
    #[mut] signer maker,
    #[mut] account escrow
  ) {
    assert(escrow.status == 1, "Escrow not accepted");
    assert(escrow.maker == maker, "Not the maker");
    escrow.status = 2;
    emit EscrowCompleted(escrow.maker, escrow.taker, escrow.amount);
  }

  pub instruction cancel_escrow(
    #[mut] signer maker,
    #[mut] account escrow
  ) {
    assert(escrow.maker == maker, "Not the maker");
    assert(escrow.status == 0, "Cannot cancel after acceptance");
    escrow.status = 3;
    emit EscrowCancelled(maker);
  }

  event EscrowCreated { maker: pubkey, amount: u64, receive_amount: u64 }
  event EscrowAccepted { taker: pubkey, amount: u64 }
  event EscrowCompleted { maker: pubkey, taker: pubkey, amount: u64 }
  event EscrowCancelled { maker: pubkey }

  error EscrowErrors {
    NotAvailable = "Escrow is not available",
    Unauthorized = "You are not authorized",
    AlreadyAccepted = "Escrow already accepted"
  }
}
`,
  },

  staking: {
    name: 'Staking Rewards',
    description: 'A staking program with configurable rewards and lock periods.',
    source: `// {name} — Staking Rewards Program
// Generated by Sigil (https://github.com/DosukaSOL/sigil)

program {name} {

  account StakePool {
    authority: pubkey,
    total_staked: u64,
    reward_rate: u64,
    min_stake: u64,
    lock_period: u64,
    is_active: bool
  }

  account StakeInfo {
    owner: pubkey,
    amount: u64,
    staked_at: u64,
    last_claim: u64,
    rewards_earned: u64
  }

  pub instruction initialize_pool(
    #[mut] signer authority,
    #[init] account pool,
    reward_rate: u64,
    min_stake: u64,
    lock_period: u64
  ) {
    pool.authority = authority;
    pool.total_staked = 0;
    pool.reward_rate = reward_rate;
    pool.min_stake = min_stake;
    pool.lock_period = lock_period;
    pool.is_active = true;
    emit PoolInitialized(authority, reward_rate);
  }

  pub instruction stake(
    #[mut] signer staker,
    #[mut] account pool,
    #[init] account info,
    amount: u64
  ) {
    assert(pool.is_active == true, "Pool is inactive");
    assert(amount >= pool.min_stake, "Below minimum stake");
    info.owner = staker;
    info.amount = amount;
    info.staked_at = Clock.slot;
    info.last_claim = Clock.slot;
    info.rewards_earned = 0;
    pool.total_staked += amount;
    emit Staked(staker, amount);
  }

  pub instruction claim_rewards(
    #[mut] signer staker,
    #[mut] account pool,
    #[mut] account info
  ) {
    assert(info.owner == staker, "Not the staker");
    let elapsed = Clock.slot - info.last_claim;
    let reward = elapsed * pool.reward_rate * info.amount / 1000000;
    info.rewards_earned += reward;
    info.last_claim = Clock.slot;
    emit RewardsClaimed(staker, reward);
  }

  pub instruction unstake(
    #[mut] signer staker,
    #[mut] account pool,
    #[mut] account info
  ) {
    assert(info.owner == staker, "Not the staker");
    let elapsed = Clock.slot - info.staked_at;
    assert(elapsed >= pool.lock_period, "Lock period not met");
    pool.total_staked -= info.amount;
    emit Unstaked(staker, info.amount);
  }

  event PoolInitialized { authority: pubkey, reward_rate: u64 }
  event Staked { staker: pubkey, amount: u64 }
  event RewardsClaimed { staker: pubkey, reward: u64 }
  event Unstaked { staker: pubkey, amount: u64 }

  error StakingErrors {
    PoolInactive = "Staking pool is not active",
    BelowMinimum = "Stake amount below minimum",
    LockNotMet = "Lock period has not elapsed"
  }
}
`,
  },

  dao: {
    name: 'DAO Governance',
    description: 'A DAO with proposals, voting, and treasury management.',
    source: `// {name} — DAO Governance Program
// Generated by Sigil (https://github.com/DosukaSOL/sigil)

program {name} {

  account DAO {
    authority: pubkey,
    name: string,
    member_count: u64,
    proposal_count: u64,
    quorum: u64,
    voting_period: u64,
    treasury_balance: u64
  }

  account Proposal {
    proposer: pubkey,
    title: string,
    description: string,
    votes_for: u64,
    votes_against: u64,
    status: u8,
    created_at: u64,
    amount: u64
  }

  account Member {
    wallet: pubkey,
    voting_power: u64,
    joined_at: u64,
    proposals_created: u64
  }

  pub instruction create_dao(
    #[mut] signer authority,
    #[init] account dao,
    name: string,
    quorum: u64,
    voting_period: u64
  ) {
    dao.authority = authority;
    dao.name = name;
    dao.member_count = 1;
    dao.proposal_count = 0;
    dao.quorum = quorum;
    dao.voting_period = voting_period;
    dao.treasury_balance = 0;
    emit DAOCreated(authority, name);
  }

  pub instruction add_member(
    #[mut] signer authority,
    #[mut] account dao,
    #[init] account member,
    wallet: pubkey,
    voting_power: u64
  ) {
    assert(dao.authority == authority, "Not the DAO authority");
    member.wallet = wallet;
    member.voting_power = voting_power;
    member.joined_at = Clock.slot;
    member.proposals_created = 0;
    dao.member_count += 1;
    emit MemberAdded(wallet, voting_power);
  }

  pub instruction create_proposal(
    #[mut] signer proposer,
    #[mut] account dao,
    #[init] account proposal,
    #[mut] account member,
    title: string,
    description: string,
    amount: u64
  ) {
    assert(member.wallet == proposer, "Not a member");
    proposal.proposer = proposer;
    proposal.title = title;
    proposal.description = description;
    proposal.votes_for = 0;
    proposal.votes_against = 0;
    proposal.status = 0;
    proposal.created_at = Clock.slot;
    proposal.amount = amount;
    dao.proposal_count += 1;
    member.proposals_created += 1;
    emit ProposalCreated(proposer, title);
  }

  pub instruction vote(
    #[mut] signer voter,
    #[mut] account proposal,
    #[mut] account member,
    in_favor: bool
  ) {
    assert(member.wallet == voter, "Not a member");
    assert(proposal.status == 0, "Voting closed");
    if in_favor {
      proposal.votes_for += member.voting_power;
    } else {
      proposal.votes_against += member.voting_power;
    }
    emit Voted(voter, in_favor);
  }

  pub instruction execute_proposal(
    #[mut] signer authority,
    #[mut] account dao,
    #[mut] account proposal
  ) {
    assert(dao.authority == authority, "Not authority");
    assert(proposal.status == 0, "Already executed");
    assert(proposal.votes_for >= dao.quorum, "Quorum not met");
    assert(proposal.votes_for > proposal.votes_against, "Not enough votes");
    proposal.status = 1;
    emit ProposalExecuted(proposal.title, proposal.votes_for);
  }

  event DAOCreated { authority: pubkey, name: string }
  event MemberAdded { wallet: pubkey, voting_power: u64 }
  event ProposalCreated { proposer: pubkey, title: string }
  event Voted { voter: pubkey, in_favor: bool }
  event ProposalExecuted { title: string, votes: u64 }

  error DAOErrors {
    Unauthorized = "You are not authorized",
    NotMember = "You are not a DAO member",
    QuorumNotMet = "Quorum threshold not reached",
    VotingClosed = "Voting period has ended"
  }
}
`,
  },

  nft: {
    name: 'NFT Collection',
    description: 'An NFT collection with mint, transfer, and metadata.',
    source: `// {name} — NFT Collection Program
// Generated by Sigil (https://github.com/DosukaSOL/sigil)

import { NFT } from "@purp/stdlib";

program {name} {

  account Collection {
    authority: pubkey,
    name: string,
    symbol: string,
    total_minted: u64,
    max_supply: u64,
    royalty_bps: u64,
    is_minting: bool
  }

  account NftMetadata {
    collection: pubkey,
    owner: pubkey,
    name: string,
    uri: string,
    mint_number: u64,
    is_listed: bool,
    price: u64
  }

  pub instruction create_collection(
    #[mut] signer authority,
    #[init] account collection,
    name: string,
    symbol: string,
    max_supply: u64,
    royalty_bps: u64
  ) {
    collection.authority = authority;
    collection.name = name;
    collection.symbol = symbol;
    collection.total_minted = 0;
    collection.max_supply = max_supply;
    collection.royalty_bps = royalty_bps;
    collection.is_minting = true;
    emit CollectionCreated(authority, name, max_supply);
  }

  pub instruction mint_nft(
    #[mut] signer minter,
    #[mut] account collection,
    #[init] account metadata,
    name: string,
    uri: string
  ) {
    assert(collection.is_minting == true, "Minting is closed");
    assert(collection.total_minted < collection.max_supply, "Max supply reached");
    collection.total_minted += 1;
    metadata.collection = collection;
    metadata.owner = minter;
    metadata.name = name;
    metadata.uri = uri;
    metadata.mint_number = collection.total_minted;
    metadata.is_listed = false;
    metadata.price = 0;
    emit NftMinted(minter, name, collection.total_minted);
  }

  pub instruction list_nft(
    #[mut] signer owner,
    #[mut] account metadata,
    price: u64
  ) {
    assert(metadata.owner == owner, "Not the owner");
    assert(price > 0, "Price must be positive");
    metadata.is_listed = true;
    metadata.price = price;
    emit NftListed(owner, metadata.name, price);
  }

  pub instruction buy_nft(
    #[mut] signer buyer,
    #[mut] account metadata,
    #[mut] account collection
  ) {
    assert(metadata.is_listed == true, "NFT not listed");
    metadata.owner = buyer;
    metadata.is_listed = false;
    metadata.price = 0;
    emit NftSold(buyer, metadata.name);
  }

  pub instruction close_minting(
    #[mut] signer authority,
    #[mut] account collection
  ) {
    assert(collection.authority == authority, "Unauthorized");
    collection.is_minting = false;
    emit MintingClosed(authority);
  }

  event CollectionCreated { authority: pubkey, name: string, max_supply: u64 }
  event NftMinted { minter: pubkey, name: string, number: u64 }
  event NftListed { owner: pubkey, name: string, price: u64 }
  event NftSold { buyer: pubkey, name: string }
  event MintingClosed { authority: pubkey }

  error NftErrors {
    MintingClosed = "Minting is closed",
    MaxSupply = "Maximum supply reached",
    NotOwner = "You do not own this NFT",
    NotListed = "NFT is not listed for sale"
  }
}
`,
  },

  game: {
    name: 'On-Chain Game',
    description: 'A simple on-chain game with player state, scores, and leaderboard.',
    source: `// {name} — On-Chain Game Program
// Generated by Sigil (https://github.com/DosukaSOL/sigil)

program {name} {

  account GameState {
    authority: pubkey,
    game_name: string,
    player_count: u64,
    prize_pool: u64,
    round: u64,
    is_active: bool
  }

  account Player {
    wallet: pubkey,
    score: u64,
    games_played: u64,
    wins: u64,
    joined_at: u64
  }

  pub instruction create_game(
    #[mut] signer authority,
    #[init] account game,
    game_name: string
  ) {
    game.authority = authority;
    game.game_name = game_name;
    game.player_count = 0;
    game.prize_pool = 0;
    game.round = 1;
    game.is_active = true;
    emit GameCreated(authority, game_name);
  }

  pub instruction register_player(
    #[mut] signer wallet,
    #[mut] account game,
    #[init] account player
  ) {
    assert(game.is_active == true, "Game is not active");
    player.wallet = wallet;
    player.score = 0;
    player.games_played = 0;
    player.wins = 0;
    player.joined_at = Clock.slot;
    game.player_count += 1;
    emit PlayerRegistered(wallet);
  }

  pub instruction play_round(
    #[mut] signer wallet,
    #[mut] account game,
    #[mut] account player,
    score: u64
  ) {
    assert(game.is_active == true, "Game is not active");
    assert(player.wallet == wallet, "Not your player");
    player.score += score;
    player.games_played += 1;
    emit RoundPlayed(wallet, score, player.score);
  }

  pub instruction claim_win(
    #[mut] signer wallet,
    #[mut] account game,
    #[mut] account player
  ) {
    assert(player.wallet == wallet, "Not your player");
    player.wins += 1;
    emit WinClaimed(wallet, player.wins);
  }

  pub instruction end_game(
    #[mut] signer authority,
    #[mut] account game
  ) {
    assert(game.authority == authority, "Unauthorized");
    game.is_active = false;
    game.round += 1;
    emit GameEnded(authority, game.round);
  }

  event GameCreated { authority: pubkey, name: string }
  event PlayerRegistered { wallet: pubkey }
  event RoundPlayed { player: pubkey, round_score: u64, total_score: u64 }
  event WinClaimed { player: pubkey, total_wins: u64 }
  event GameEnded { authority: pubkey, round: u64 }

  error GameErrors {
    NotActive = "Game is not active",
    Unauthorized = "You are not authorized",
    NotYourPlayer = "This is not your player account"
  }
}
`,
  },
};

export function getTemplate(templateName: string, programName?: string): PurpTemplate | null {
  const key = templateName.toLowerCase().replace(/[\s-]/g, '');
  const aliases: Record<string, string> = {
    token: 'token',
    spl: 'token',
    spltoken: 'token',
    escrow: 'escrow',
    trade: 'escrow',
    swap: 'escrow',
    staking: 'staking',
    stake: 'staking',
    rewards: 'staking',
    dao: 'dao',
    governance: 'dao',
    vote: 'dao',
    voting: 'dao',
    nft: 'nft',
    collection: 'nft',
    mint: 'nft',
    game: 'game',
    gaming: 'game',
    onchain: 'game',
  };

  const resolved = aliases[key] ?? key;
  const template = TEMPLATES[resolved];
  if (!template) return null;

  const name = programName ?? template.name.replace(/\s+/g, '');
  return {
    ...template,
    source: template.source.replace(/\{name\}/g, name),
  };
}

export function listTemplates(): string {
  return Object.entries(TEMPLATES)
    .map(([key, t]) => `- **${key}**: ${t.name} — ${t.description}`)
    .join('\n');
}
